"""add_thinking_and_tool_steps_to_messages

Revision ID: 06bd849e2d45
Revises: 12dc19c2e570
Create Date: 2026-04-26 03:06:20.167406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '06bd849e2d45'
down_revision: Union[str, None] = '12dc19c2e570'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('thinking', sa.Text(), nullable=True))
    op.add_column('messages', sa.Column('tool_steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'tool_steps')
    op.drop_column('messages', 'thinking')
    # ### end Alembic commands ###
